version: '3'
services:
  vue-app:
    build:
      context: .
      target: production
    ports:
      - "8081:80"
    restart: always
    env_file:
      - .env.production
    networks:
      - labnet-upi

networks:
  labnet-upi:
    external: true
